### ISSUE TITLE
Incorrect level shift on LCD TH Screws and Dupont schematic

### ISSUE THREAD

**Issue by wvolz** [thorrak/brewpi-esp8266#29]
The LCD TH and Dupont schematics incorrectly have the SDA I2C line connected to a one way voltage divider for conversion from 5V to 3.3V (in red box below). The fix is to either move to a different level converter board or to move the D2 connection to the second bi-directional converter on the level shifter board (in green below).

![20190821 brewpi-esp8266 th screws](https://user-images.githubusercontent.com/404202/63472400-3b5d7b80-c42f-11e9-820e-5e1dfdf76c5c.png)

It looks like the schematic was built around [this level converter](https://www.sparkfun.com/products/retired/11978), but [there is a version](https://www.sparkfun.com/products/12009) with 4 bi-directional shifters that should work as a drop-in replacement.

The schematic/board should be updated to show the correct level converter. I can submit a revised board+schematic if that would help.

**Comment by thorrak** [comment]
If you don’t mind, that would be very helpful!

Sent from my iPhone

On Aug 21, 2019, at 6:21 PM, wvolz <notifications@github.com<mailto:notifications@github.com>> wrote:


The LCD TH and Dupont schematics incorrectly have the SDA I2C line connected to a one way voltage divider for conversion from 5V to 3.3V (in red box below). The fix is to either move to a different level converter board or to move the D2 connection to the second bi-directional converter on the level shifter board (in green below).

[20190821 brewpi-esp8266 th screws]<https://user-images.githubusercontent.com/404202/63472400-3b5d7b80-c42f-11e9-820e-5e1dfdf76c5c.png>

It looks like the schematic was built around this level converter<https://www.sparkfun.com/products/retired/11978>, but there is a version<https://www.sparkfun.com/products/12009> with 4 bi-directional shifters that should work as a drop-in replacement.

The schematic/board should be updated to show the correct level converter. I can submit a revised board+schematic if that would help.

**Comment by lalo-uy** [comment]
There is a quick hack that allow the I2C interface for the LCD to work on
3,3V and the LCD at 5V

https://www.instructables.com/id/Raspberry-Pi-Using-1-I2C-LCD-Backpacks-for-1602-Sc/

No need for level translators

**Comment by wvolz** [comment]
@thorrak pull request submitted with fix. Attached is a screenshot of the change.

![image](https://user-images.githubusercontent.com/404202/63628305-f8371000-c5c8-11e9-8637-155814b7e8ce.png)

![image](https://user-images.githubusercontent.com/404202/63628321-0f75fd80-c5c9-11e9-8dc8-649dd3ec0d35.png)

**Comment by wvolz** [comment]
@lalo-uy You are correct that changing the I2C backpack board would eliminate the need for level shifters.

**Comment by thorrak** [comment]
As @wvolz noted, the module included was incorrect. I've updated all of the PCBs since so hopefully this is now resolved.

Apologies for the delay in getting this out there!
