### ISSUE TITLE
Issue with the RJ-45 v1.1.brd file

### ISSUE THREAD

**Issue by vihar17** [thorrak/brewpi-esp8266#39]
Hello,
I have an issue with the "RJ-45 v1.1.brd" file.
When I upload the file to oshpark, a pcb manufacter, the board has only 6 holes. It looks like it's made for the RJ11 connector.

Also, I haven't found what the RJ45 "Top routed" board means.

Thank you

**Comment by thorrak** [comment]
Just FYI - All of the PCBs in my repo are old. Let me know what PCBs you want, and I'll attach them here. The repo will get updated in the near future, but I need to fix a few PCBs first.

**Comment by vihar17** [comment]
Thank you for your answer.

I'm looking for the D1 Mini Mosfet board (shown here : https://github.com/brewpi-remix/brewpi-pcb-rmx/tree/master/D1%20Breakout)
And the RJ45 board (shown here : https://github.com/thorrak/brewpi-esp8266/blob/master/hardware/BrewPi%20Sensor%20Boards/RJ-45%20Sensor%20Breakout.md)

**Comment by thorrak** [comment]
The D1 mini mosfet board is @lbussy 's creation - I think he does a better job than I do keeping his files up to date, so I'm guessing that one is OK. 

The RJ45 board shouldn't ahve changed much, but I believe the latest design is this one:

[RJ-45 Top Routed.zip](https://github.com/thorrak/brewpi-esp8266/files/4665162/RJ-45.Top.Routed.zip)

**Comment by vihar17** [comment]
Thank you very much !

**Comment by lbussy** [comment]
The [D1 TH Mosfet board](https://github.com/brewpi-remix/brewpi-pcb-rmx/tree/master/ESP8266%20Boards/WeMos%20D1%20Mini%20Breakout) is mine, [the corresponding breakout](https://github.com/brewpi-remix/brewpi-pcb-rmx/tree/master/ESP8266%20Boards/RJ45%20Breakout) is this one.  There was a small error on the silk screening only on that board, which reversed the pinout.  Electrically it was correct and matched @thorrak 's specification.  I corrected the silkscreen this morning.

Being early in the morning, I have not looked to see if @thorrak has a TH MOSFET board.  I suspect not since he and I have "artistic differences."  :stuck_out_tongue_winking_eye:  Pinout-wise, my boards are interchangeable.

(BTW:  I moved the folder structure on mine this morning to make it a little less confusing.)

**Comment by vihar17** [comment]
Oh crap I ordered another pcb...
May I ask why the GND isn't linked to anything on your board ?
I thought it was a mistake, which is why I ordered this board : https://aisler.net/p/SDEFMNWJ
Will it be compatible with your Mosfet board ?

Sorry for the aisler link, I don't remember where I found it originally

**Comment by lbussy** [comment]
> May I ask why the GND isn't linked to anything on your board ?

To whom are you addressing that question?

**Comment by thorrak** [comment]
> > May I ask why the GND isn't linked to anything on your board ?
> 
> To whom are you addressing that question?

I think me, because I think that board had a ground plane on the back. At least, I _hope_ it had a ground plane on the back.

**Comment by vihar17** [comment]
> [the corresponding breakout](https://github.com/brewpi-remix/brewpi-pcb-rmx/tree/master/ESP8266%20Boards/RJ45%20Breakout) is this one

I'm talking about this board. It seems like GND isn't connected to anything (see here : https://aisler.net/p/BJRXNPCS)

**Comment by lbussy** [comment]
What "issue"?  I assure you it is connected, at least when I open it (and had them manufactured.)

**Comment by vihar17** [comment]
Thank you for the information.
My mistake.
